package com.stargate.statusquery.edd.application.entity;

public enum States {
	PLACED,
	ACCEPTED,
	REJECTED,
	DEBIT_PLACED,
	DEBIT_COMPLETE,
	DEBIT_FAIL,
	CREDIT_PLACED,
	CREDIT_COMPLETE,
	CREDIT_FAIL,
	DEBIT_ROLLBACK_PLACED,
	DEBIT_ROLLBACK_COMPLETE,
	DEBIT_ROLLBACK_FAIL,
	CREDIT_ROLLBACK_PLACED,
	CREDIT_ROLLBACK_COMPLETE,
	CREDIT_ROLLBACK_FAIL,
	COMPLETED
}
